from algorithms.pca import Pca
from algorithms.k_means import Kmeans
from algorithms.linear_regression import Linearregression
from algorithms.logistic_regression import Logisticregression
from algorithms.support_vector_machines import SupportVectorMachines
from algorithms.grid_search import GridSearch
from algorithms.k_nearest_neighbors import KNearestNeighbors